import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { CartContextProvider } from "./context/CartContext";
import vazir from "@/fonts/vazir/vazir";

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>
        {/* <CartContextProvider> */}
          <Layout>{children}</Layout>
        {/* </CartContextProvider> */}
      </body>
    </html>
  );
}
